### ISSUE TITLE
`apiname` is the proxy name? 

### ISSUE THREAD

**Issue by earth2marsh** [DinoChiesa/ApigeeEdge-API-Traffic-Summarizer#1]
In [this image](https://github.com/DinoChiesa/ApigeeEdge-API-Traffic-Summarizer/blob/master/images/screenshot-20180907-083518.png?raw=true), the column API name represents the proxy name, yes? Might be less ambiguous to say that instead.

**Comment by DinoChiesa** [comment]
Fixed in commit f484faefcccaf3491d33c5ed6367d2ea2227c672
